// Generated by https://quicktype.io

import type { ReadingWithMeter } from 'modules/readings/types/reading.types';
import type { Invoice } from './invoice.types';

export interface InvoicesDelinquent {
  result: Result[];
}

export interface Result {
  ci: string;
  name: string;
  surname: string;
  totalDebt: number;
  totalInvoices: number;
  meters: MeterElement[];
}

export interface MeterElement {
  meterId: string;
  meterNumber: number;
  totalDebt: number;
  invoicesCount: number;
  oldestDebt: Date;
  invoices: InvoiceWithReadingMeter[];
}

export type InvoiceWithReadingMeter = Invoice & {
  reading: ReadingWithMeter;
};

export interface Month {
  date: Date;
  value: number;
}
